Spring:
    datasource:
      url: jdbc:mysql://localhost:3306/usersspring?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      username: root
      password:
